<a href="https://colab.research.google.com/github/JFzta/Differential-Equations-Codes/blob/main/ExamenParcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install -Uqq ipdb
import ipdb

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 20.2 MB/s eta 0:00:00


In [3]:
import numpy as np
from scipy.linalg import lu, solve

x = np.array([0.5, 1.8, 3.2])
fx = np.array([1.25, -0.96, 0.44])


A = np.vstack([np.ones_like(x), x, x**2]).T
b = fx

P, L, U = lu(A)

Pb = P @ b
y = np.linalg.solve(L, Pb)

c = np.linalg.solve(U, y)


print("Matriz A:")
print(A)
print("\nMatriz L:")
print(L)
print("\nMatriz U:")
print(U)
print("\nVector c (coeficientes c1, c2, c3):")
print(c)# VERIFICAR -----------------------------------




Matriz A:
[[ 1.    0.5   0.25]
 [ 1.    1.8   3.24]
 [ 1.    3.2  10.24]]

Matriz L:
[[1.         0.         0.        ]
 [1.         1.         0.        ]
 [1.         0.48148148 1.        ]]

Matriz U:
[[ 1.    0.5   0.25]
 [ 0.    2.7   9.99]
 [ 0.    0.   -1.82]]

Vector c (coeficientes c1, c2, c3):
[ 3. -4.  1.]


In [4]:
import numpy as np

# Definimos la matriz A
A = np.array([
    [12, 3, -5],
    [1, 5, 3],
    [3, 7, 13]
])

# Verificación de diagonal dominante
def es_diagonal_dominante(A):
    for i in range(len(A)):
        diagonal = abs(A[i, i])
        suma_otras = sum(abs(A[i, j]) for j in range(len(A)) if j != i)
        print(f"Fila {i+1}: |a_ii| = {diagonal}, suma = {suma_otras}")
        if diagonal < suma_otras:
            return False
    return True

print("¿Es diagonalmente dominante?:", es_diagonal_dominante(A))

#--------------------------JACOBI----------------------------------------------------------
# Sistema lineal
b = np.array([1, 28, 76])
x0 = np.array([1.0, 0.0, 1.0])  # condición inicial
n_iter = 10

def jacobi(A, b, x0, n_iter):
    n = len(b)
    x = x0.copy()
    resultados = []

    for k in range(n_iter):
        x_new = np.zeros_like(x)
        errores = []
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
            error = abs((x_new[i] - x[i]) / x_new[i]) * 100 if x_new[i] != 0 else 0
            errores.append(error)
        resultados.append((k + 1, *x_new, *errores))
        x = x_new
    return resultados

# Ejecutar
res_jacobi = jacobi(A, b, x0, n_iter)

# Mostrar resultados
print("Iter |   x1      x2      x3   |  Err_x1  Err_x2  Err_x3")
for r in res_jacobi:
    print(f"{r[0]:>4} | {r[1]:7.4f} {r[2]:7.4f} {r[3]:7.4f} | {r[4]:7.2f} {r[5]:7.2f} {r[6]:7.2f}")

Fila 1: |a_ii| = 12, suma = 8
Fila 2: |a_ii| = 5, suma = 4
Fila 3: |a_ii| = 13, suma = 10
¿Es diagonalmente dominante?: True
Iter |   x1      x2      x3   |  Err_x1  Err_x2  Err_x3
   1 |  0.5000  4.8000  5.6154 |  100.00  100.00   82.19
   2 |  1.2231  2.1308  3.1462 |   59.12  125.27   78.48
   3 |  0.8615  3.4677  4.4166 |   41.96   38.55   28.76
   4 |  1.0566  2.7778  3.7801 |   18.46   24.84   16.84
   5 |  0.9639  3.1206  4.1066 |    9.62   10.99    7.95
   6 |  1.0143  2.9433  3.9434 |    4.96    6.03    4.14
   7 |  0.9906  3.0311  4.0273 |    2.39    2.90    2.08
   8 |  1.0036  2.9855  3.9854 |    1.29    1.53    1.05
   9 |  0.9975  3.0080  4.0070 |    0.61    0.75    0.54
  10 |  1.0009  2.9963  3.9962 |    0.33    0.39    0.27


In [5]:
def gauss_seidel(A, b, x0, n_iter):
    n = len(b)
    x = x0.copy()
    resultados = []

    for k in range(n_iter):
        x_old = x.copy()
        errores = []
        for i in range(n):
            s1 = sum(A[i][j] * x[j] for j in range(i))
            s2 = sum(A[i][j] * x_old[j] for j in range(i + 1, n))
            x[i] = (b[i] - s1 - s2) / A[i][i]
            error = abs((x[i] - x_old[i]) / x[i]) * 100 if x[i] != 0 else 0
            errores.append(error)
        resultados.append((k + 1, *x, *errores))
    return resultados

# Ejecutar
res_gs = gauss_seidel(A, b, x0, n_iter)

# Mostrar resultados
print("\nMétodo de Gauss-Seidel:")
print("Iter |   x1      x2      x3   |  Err_x1  Err_x2  Err_x3")
for r in res_gs:
    print(f"{r[0]:>4} | {r[1]:7.4f} {r[2]:7.4f} {r[3]:7.4f} | {r[4]:7.2f} {r[5]:7.2f} {r[6]:7.2f}")


Método de Gauss-Seidel:
Iter |   x1      x2      x3   |  Err_x1  Err_x2  Err_x3
   1 |  0.5000  4.9000  3.0923 |  100.00  100.00   67.66
   2 |  0.1468  3.7153  3.8118 |  240.61   31.89   18.87
   3 |  0.7428  3.1644  3.9708 |   80.24   17.41    4.01
   4 |  0.9468  3.0281  3.9971 |   21.55    4.50    0.66
   5 |  0.9918  3.0034  4.0001 |    4.54    0.82    0.07
   6 |  0.9992  3.0001  4.0001 |    0.74    0.11    0.00
   7 |  1.0000  2.9999  4.0000 |    0.08    0.01    0.00
   8 |  1.0000  3.0000  4.0000 |    0.00    0.00    0.00
   9 |  1.0000  3.0000  4.0000 |    0.00    0.00    0.00
  10 |  1.0000  3.0000  4.0000 |    0.00    0.00    0.00


In [6]:
import numpy as np
import pandas as pd

# Definir la función
def f(x):
    return x**2 * np.sqrt(np.cos(x))

# Intervalo y paso
h = 0.01
x_vals = np.arange(1.25, 1.35 + h, h)

# Evaluar la función en todos los puntos
tabla = [(x, f(x)) for x in x_vals]

# Calcular la segunda derivada en x = 1.3
x0 = 1.3
f_xph = f(x0 + h)
f_x = f(x0)
f_xmh = f(x0 - h)

f2_num = (f_xph - 2*f_x + f_xmh) / h**2

# Mostrar tabla
df = pd.DataFrame(tabla, columns=["x", "f(x)"])
print(df)

# Mostrar resultado de la segunda derivada
print(f"\nAproximación de f''(1.3): {f2_num:.6f}")


       x      f(x)
0   1.25  0.877400
1   1.26  0.877954
2   1.27  0.877929
3   1.28  0.877294
4   1.29  0.876020
5   1.30  0.874073
6   1.31  0.871417
7   1.32  0.868015
8   1.33  0.863825
9   1.34  0.858802
10  1.35  0.852896
11  1.36  0.846055

Aproximación de f''(1.3): -7.084073


In [7]:
import numpy as np

# Definir la función
def f(x):
    return x**2 * np.sqrt(np.cos(x))

# Intervalo
a = 1.25
b = 1.35

# Regla del trapecio (n = 1)
def trapecio(f, a, b):
    return (b - a) / 2 * (f(a) + f(b))

# Regla de Simpson 1/3 (n = 2)
def simpson_1_3(f, a, b):
    m = (a + b) / 2
    return (b - a) / 6 * (f(a) + 4*f(m) + f(b))

# Regla de Simpson 3/8 (n = 3)
def simpson_3_8(f, a, b):
    h = (b - a) / 3
    x0 = a
    x1 = a + h
    x2 = a + 2*h
    x3 = b
    return (b - a) * (f(x0) + 3*f(x1) + 3*f(x2) + f(x3)) / 8

# Calcular las integrales
I_trapecio = trapecio(f, a, b)
I_simpson13 = simpson_1_3(f, a, b)
I_simpson38 = simpson_3_8(f, a, b)

print(f"Trapecio:         {I_trapecio:.8f}")
print(f"Simpson 1/3:      {I_simpson13:.8f}")
print(f"Simpson 3/8:      {I_simpson38:.8f}")


Trapecio:         0.08651479
Simpson 1/3:      0.08710979
Simpson 3/8:      0.08711033
