<a href="https://colab.research.google.com/github/JFzta/Differential-Equations-Codes/blob/main/ExamenParcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install -Uqq ipdb
import ipdb

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 19.7 MB/s eta 0:00:00


In [1]:
import numpy as np
from scipy.linalg import lu, solve

# Datos
x = np.array([0.5, 1.8, 3.2])
fx = np.array([1.25, -0.96, 0.44])

# Construcción de la matriz A y vector b
A = np.vstack([np.ones_like(x), x, x**2]).T
b = fx

# Descomposición LU
P, L, U = lu(A)

# Paso 1: resolver Ly = Pb
Pb = P @ b
y = np.linalg.solve(L, Pb)

# Paso 2: resolver Uc = y
c = np.linalg.solve(U, y)

# Mostrar resultados
print("Matriz A:")
print(A)
print("\nMatriz L:")
print(L)
print("\nMatriz U:")
print(U)
print("\nVector c (coeficientes c1, c2, c3):")
print(c)# VERIFICAR -----------------------------------




Matriz A:
[[ 1.    0.5   0.25]
 [ 1.    1.8   3.24]
 [ 1.    3.2  10.24]]

Matriz L:
[[1.         0.         0.        ]
 [1.         1.         0.        ]
 [1.         0.48148148 1.        ]]

Matriz U:
[[ 1.    0.5   0.25]
 [ 0.    2.7   9.99]
 [ 0.    0.   -1.82]]

Vector c (coeficientes c1, c2, c3):
[ 3. -4.  1.]


In [4]:
import numpy as np

# Definimos la matriz A
A = np.array([
    [12, 3, -5],
    [1, 5, 3],
    [3, 7, 13]
])

# Verificación de diagonal dominante
def es_diagonal_dominante(A):
    for i in range(len(A)):
        diagonal = abs(A[i, i])
        suma_otras = sum(abs(A[i, j]) for j in range(len(A)) if j != i)
        print(f"Fila {i+1}: |a_ii| = {diagonal}, suma = {suma_otras}")
        if diagonal < suma_otras:
            return False
    return True

print("¿Es diagonalmente dominante?:", es_diagonal_dominante(A))

#--------------------------JACOBI----------------------------------------------------------
# Sistema lineal
b = np.array([1, 28, 76])
x0 = np.array([1.0, 0.0, 1.0])  # condición inicial
n_iter = 10

def jacobi(A, b, x0, n_iter):
    n = len(b)
    x = x0.copy()
    resultados = []

    for k in range(n_iter):
        x_new = np.zeros_like(x)
        errores = []
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
            error = abs((x_new[i] - x[i]) / x_new[i]) * 100 if x_new[i] != 0 else 0
            errores.append(error)
        resultados.append((k + 1, *x_new, *errores))
        x = x_new
    return resultados

# Ejecutar
res_jacobi = jacobi(A, b, x0, n_iter)

# Mostrar resultados
print("Iter |   x1      x2      x3   |  Err_x1  Err_x2  Err_x3")
for r in res_jacobi:
    print(f"{r[0]:>4} | {r[1]:7.4f} {r[2]:7.4f} {r[3]:7.4f} | {r[4]:7.2f} {r[5]:7.2f} {r[6]:7.2f}")

Fila 1: |a_ii| = 12, suma = 8
Fila 2: |a_ii| = 5, suma = 4
Fila 3: |a_ii| = 13, suma = 10
¿Es diagonalmente dominante?: True
Iter |   x1      x2      x3   |  Err_x1  Err_x2  Err_x3
   1 |  0.5000  4.8000  5.6154 |  100.00  100.00   82.19
   2 |  1.2231  2.1308  3.1462 |   59.12  125.27   78.48
   3 |  0.8615  3.4677  4.4166 |   41.96   38.55   28.76
   4 |  1.0566  2.7778  3.7801 |   18.46   24.84   16.84
   5 |  0.9639  3.1206  4.1066 |    9.62   10.99    7.95
   6 |  1.0143  2.9433  3.9434 |    4.96    6.03    4.14
   7 |  0.9906  3.0311  4.0273 |    2.39    2.90    2.08
   8 |  1.0036  2.9855  3.9854 |    1.29    1.53    1.05
   9 |  0.9975  3.0080  4.0070 |    0.61    0.75    0.54
  10 |  1.0009  2.9963  3.9962 |    0.33    0.39    0.27
